---
name: test
timeout: 1800
source:
  batch_size: 375
  concurency: 32
  interval: 100
  fields:
  - name: time
    type: timestamp
    timestamp_format: '2006-01-02 15:04:05.000000'
  - name: timestamp
    type: timestamp_int
  - name: value
    type: int
    limit:
    - 0
    - 10000

sinks:
- type: materialize
  properties: {}

observer:
  type: materialize
  properties:
    metric: throughput
    query: SELECT '1' as a, count(*)/10 FROM test WHERE mz_logical_timestamp()  < timestamp + 10000 GROUP BY a
