---
name: test_orders
timeout: 120
source:
  batch_size: 2
  concurency: 2
  interval: 1000
  interval_delta: 0
  fields:
  - name: ordertime
    type: timestamp_int
    timestamp_format: '2006-01-02 15:04:05.000000'
  - name: orderid
    type: generate
    rule: "O{number:1,1000}"
  - name: itemid
    type: generate
    rule: "I{number:1,1000}"
  - name: orderunits
    type: float
    limit: [0.0, 10.0]
  - name: city
    type: generate
    rule: "{city}"
  - name: state
    type: generate
    rule: "{state}"
  - name: zipcode
    type: generate
    rule: "{zip}"
  - name: time
    type: timestamp
    timestamp_format: '2006-01-02 15:04:05.000000'
  - name: timestamp
    type: timestamp_int
  - name: value
    type: int
    limit:
    - 0
    - 10
sinks:
- type: kafka
  properties:
    brokers: pkc-ld537.ca-central-1.aws.confluent.cloud:9092
    sasl: plain
    username: ***
    password: ***
observer:
  type: kafka
  properties:
    topic: test_orders
    brokers: pkc-ld537.ca-central-1.aws.confluent.cloud:9092
    sasl: plain
    username: ***
    password: ***
    metric: latency
