---
name: order
timeout: 120000
source:
  batch_size: 1
  concurency: 1
  interval: 1000
  interval_delta: 0
  fields:
  - name: ordertime
    type: timestamp_int
    timestamp_format: '2006-01-02 15:04:05.000000'
  - name: orderid
    type: generate
    rule: "O{number:1,1000}"
  - name: itemid
    type: generate
    rule: "I{number:1,1000}"
  - name: orderunits
    type: float
    limit: [0.0, 10.0]
  - name: city
    type: generate
    rule: "{city}"
  - name: state
    type: generate
    rule: "{state}"
  - name: zipcode
    type: generate
    rule: "{zip}"
  - name: time
    type: timestamp
    timestamp_format: '2006-01-02 15:04:05.000000'
    timestamp_locale: 'America/Los_Angeles'
  - name: timestamp
    type: timestamp_int
  - name: value
    type: int
    limit:
    - 0
    - 10
  
sinks:
- type: kafka
  properties:
    brokers: localhost:9092

observer:
  type: kafka
  properties:
    topic: order
    brokers: localhost:9092
    metric: latency

