---
name: test
timeout: 100000000
source:
  batch_size: 4
  concurency: 1
  interval: 3000
  interval_delta: 0
  batch_number: 100000000
  random_event: true
  fields:
    - name: v
      type: int
      limit:
        - 0
        - 100
    - name: sym
      type: int
      limit:
        - 0
        - 10000
    - name: time
      type: timestamp_int
sinks:
  - type: kdb
    properties:
      host: localhost
      port: 5001

observer:
  type: kdb
  properties:
    host: localhost
    port: 5001
    metric: availability
