---
name: test
timeout: 100000000
source:
  batch_size: 4
  concurency: 1
  interval: 3000
  interval_delta: 0
  batch_number: 100
  random_event: true
  fields:
    - name: ordertime
      type: timestamp
      timestamp_format: "2006-01-02T15:04:05.000Z"
    - name: orderid
      type: generate
      rule: "O{number:1,1000}"
    - name: itemid
      type: generate
      rule: "I{number:1,1000}"
    - name: orderunits
      type: float
      limit: [0.0, 10.0]
    - name: city
      type: generate
      rule: "{city}"
    - name: state
      type: generate
      rule: "{state}"
    - name: zipcode
      type: generate
      rule: "{zip}"
    - name: t1
      type: timestamp
      timestamp_format: "2006-01-02T15:04:05.000Z"
    - name: t2
      type: timestamp_int
    - name: val
      type: int
      limit:
        - 0
        - 100000
sinks:
  - type: kdb
    properties:
      host: localhost
      port: 5001

observer:
  type: kdb
  properties:
    host: localhost
    port: 5001
    metric: availability
    query: count test
