---
name: test
timeout: 120
source:
  batch_size: 512
  concurency: 8
  interval: 100
  interval_delta: 0
  batch_number: 100000000
  fields:
  - name: value
    type: int
    limit:
    - 0
    - 100
  - name: time
    type: timestamp
    timestamp_format: '2006-01-02 15:04:05.000000'
sinks:
- type: neutron
  properties:
    address: http://localhost:8000
observer:
  type: neutron
  properties:
    address: http://localhost:8000
    query: select * from test where value=9
    time_column: time
    metric: latency
