---
name: test
timeout: 20
source:
  batch_size: 512
  concurency: 8
  interval: 100
  interval_delta: 0
  batch_number: 100000000
  random_event: true
  fields:
    - name: value
      type: int
      limit:
        - 0
        - 10000
    - name: time
      type: timestamp_int
sinks:
  - type: proton
    properties:
      host: localhost
      port: 8123
# observer:
#   type: proton
#   properties:
#     host: localhost
#     query: select * from test where value=9
#     time_column: time
#     metric: latency
observer:
  type: proton
  properties:
    host: localhost
    query: select window_start, count(*) as count from tumble(test,_tp_time, 1s) group by window_start
    time_column: time
    metric: throughput

