version: "3.6"

services:
  namesrv:
    image: apache/rocketmq:4.9.3
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:4.9.3
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/home/rocketmq/conf/broker.conf
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/conf/broker.conf
    depends_on:
      - namesrv