version: "3.6"

services:
  so1:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Password!
      - SPLUNK_HEC_TOKEN=abcd1234
    ports:
      - 8000:8000
      - 8088:8088