version: "3.7"
services:
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:20.11.3 
    volumes:
      - ./data/config:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
      - "9004:9004"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        reservations:
          memory: 4096M
  tsbs:
    container_name: tsbs
    image: timeplus/tsbs:20220629

